### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by bcongdon** [acm-uiuc/groot-request-service#3]

**Comment by therishidesai** [comment]
I have everything in the Dockerfile setup except for the port. What port should I use?

**Comment by aashishkapur** [comment]
It's up to you

**Comment by bcongdon** [comment]
@apache8080 Look in the [docker-compose file](https://github.com/acm-uiuc/groot/blob/master/docker-compose-prod.yml) and pick one that hasn't been used. 🙂
